import { ICheckinOutService } from '../interfaces/ICheckinOutService';
import { CheckinStatus } from '../models/CheckinOutService/CheckinStatus';
import { Checkin } from '../models/CheckinOutService/Checkin';
import { AccessArea } from '../models/CheckinOutService/AccessArea';
import { CurrentCheckins } from '../models/CheckinOutService/CurrentCheckins';
import { CommandResult } from '../models/CheckinOutService/CommandResult';
import { CheckinCommand } from '../models/CheckinOutService/CheckinCommand';
import { CheckinOutCommandResult } from '../models/CheckinOutService/CheckinOutCommandResult';
import { CheckoutCommand } from '../models/CheckinOutService/CheckoutCommand';
import { AccessAreaInformation } from '../models/CheckinOutService/AccessAreaInformation';
export declare class CheckinOutService implements ICheckinOutService {
    host: string;
    port: number;
    version: string;
    baseUrl: string;
    constructor(host: string, port: number, version: string);
    getAccessAreasAvailable(): Promise<AccessArea[]>;
    getAccessAreasInformation(accessArea: string): Promise<AccessAreaInformation>;
    getCheckins(customerId: number): Promise<Checkin[]>;
    getCheckinStatus(customerId: number): Promise<CheckinStatus>;
    getCurrentCheckinCount(studioNumber: number): Promise<CurrentCheckins>;
    getCustomersPresent(studioNumber?: number): Promise<CheckinStatus[]>;
    isAccessAllowed(customerId: number, timeSlotRequired: boolean, checkOpeningHours: boolean, accessAreas?: string[]): Promise<boolean>;
    isCheckoutAllowed(customerId: number): Promise<boolean>;
    getCurrentCheckinCounts(): Promise<CurrentCheckins[]>;
    checkin(customerId: number, checkinCommand: CheckinCommand): Promise<CheckinOutCommandResult>;
    checkout(customerId: number, checkoutCommand: CheckoutCommand): Promise<CheckinOutCommandResult>;
    enterLocation(customerId: number, location: string, studioNumber: number): Promise<any>;
    leaveLocation(customerId: number, studioNumber: number): Promise<any>;
    setAccessGrantedTill(customerId: number, accessGrantedTill: string): Promise<any>;
    removeAccessGrantedTill(customerId: number): Promise<any>;
    getAccessAreasCurrentlyAllowed(customerId: number): Promise<AccessArea[]>;
    updateCheckinRemark(customerId: number, checkinRemark: string): Promise<CommandResult>;
}
